Also Look for the Amazon cred header to remove auth header
electron-userland/electron-builder pull request #5594
Opened 2021-01-28 23:27 UTC by GaryCaldwell

Looks like the amazon dual auth problem is now on other urls than amazonaws.com because github releases is using it now too

2021-01-30 17:34 UTC, GaryCaldwell commented
The CI failures seem to be unrelated and failing on all PRs.

2021-02-05 00:25 UTC, 9oelM commented
Some people are desperately waiting for this.. 😢

2021-02-07 08:08 UTC, lsitest requested changes
There is no need for two nested ifs for the delete condition.
The second one which has the condition : 
"(parsedNewUrl.hostname.endsWith(".amazonaws.com") || parsedNewUrl.searchParams.has("X-Amz-Credential"))", is enough to get things working again.

2021-02-07 17:05 UTC, hypermoose commented
@lsitest Your likely right but I didnt want to regress anything so I was being conservative

2021-02-09 04:51 UTC, leonetosoft commented
Complicated, updating everyone is immensely complicated! Many users who do not know how to update manual! what if the update is critical?

2021-02-09 12:16 UTC, 9oelM commented
Please help thousands of poor and lost souls throughout the world by merging this PR. Who can approve this PR?

2021-02-09 23:52 UTC, Chrisbright10 approved these changes
looks great!

2021-02-09 23:56 UTC, Chrisbright10 commented
> There is no need for two nested ifs for the delete condition.
> The second one which has the condition :
> "(parsedNewUrl.hostname.endsWith(".amazonaws.com") || parsedNewUrl.searchParams.has("X-Amz-Credential"))", is enough to get things working again.

He didn't add any "if"s, he only modified the one that was already there. no reason to change it and potentially break functionality.

2021-02-10 00:11 UTC, Bernix01 commented
So is this happening?

2021-02-14 17:24 UTC, mmaietta approved these changes

2021-02-15 15:21 UTC, 9oelM commented
The number of the poor souls is only increasing in number as the time goes. What it really takes is just to approve a commit of 7 lines of difference, one of which is a new line addition. 6 lines. I really hope that someone with the right to approve this PR exercises it at the very right time, and be the hero of the world just by pressing a few sequence of simple buttons.

2021-02-16 12:42 UTC, adelphes commented
@Chrisbright10 @mmaietta - can you please merge this in so we can all move on with our lives.

It's been 18 days since updates were [reported](https://github.com/electron-userland/electron-builder/issues/5595) broken - this PR, which presumably will fix it, is 19 days old.
It's a one-line change with 2 approvals.

What are the electron-builder maintainers waiting for?

2021-02-16 16:25 UTC, mmaietta commented
I'm really sorry @adelphes, I wish I could help more. I'm actually not a maintainer and don't have write access ☹️  I'm hoping to change that though.

I've opened https://github.com/electron-userland/electron-builder/pull/5630 to fix master branch so that (I'm presuming) it'd unblock a pre-release cut after this PR is merged. 

@develar can you please assist here?

2021-02-16 16:28 UTC, merged

2021-02-16 16:47 UTC, adelphes commented
@mmaietta thanks very much and apologies - as a reviewer, I'd assumed you have write access.
Thanks for bumping this.